# Generated by Django 4.1.6 on 2023-02-09 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inrite', '0002_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='edition',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
