# Generated by Django 4.1.6 on 2023-02-09 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inrite', '0005_alter_news_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 2, 9, 13, 20, 50, 849135)),
        ),
    ]
