# Generated by Django 4.1.6 on 2023-02-09 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inrite', '0007_alter_news_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 9, 16, 26, 39, 941934, tzinfo=datetime.timezone.utc)),
        ),
    ]
