# Generated by Django 4.1.6 on 2023-02-09 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inrite', '0012_news_description_alter_news_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 9, 18, 44, 11, 335680, tzinfo=datetime.timezone.utc), verbose_name='date_publish'),
        ),
    ]
