# Generated by Django 4.1.6 on 2023-02-10 01:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inrite', '0015_alter_news_author_alter_news_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 10, 1, 12, 26, 755830, tzinfo=datetime.timezone.utc), verbose_name='date_publish'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='news/'),
        ),
    ]
